const $=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let pageIndex=0,simStep=0,navTimer,notesOpen=false;const state={A:{id:23,r:0,final:false},B:{id:139,r:0,final:false}};
function resize(){let s=Math.min(innerWidth/1600,innerHeight/900);$('stage').style.transform=`translate(-50%,-50%) scale(${s})`;}
function showNav(){$('nav').classList.add('show');clearTimeout(navTimer);navTimer=setTimeout(()=>$('nav').classList.remove('show'),1700);}
function showPage(){document.querySelectorAll('.page').forEach((e,i)=>e.classList.toggle('active',i===pageIndex));$('pageNo').textContent=`${pageIndex+1} / 9`;$('prev').disabled=pageIndex===0;$('next').disabled=pageIndex===8;$('advance').disabled=![3,4,5].includes(pageIndex);let n=NARRATION[pageIndex];$('notes').innerHTML='<b>排练讲稿：正式录制前按 T 隐藏</b><h3>'+E(n.time+' · '+n.title)+'</h3><p>'+E(n.action)+'</p><p>'+E(n.voice)+'</p>';}
function move(d){closeOverlay();pageIndex=Math.min(8,Math.max(0,pageIndex+d));showPage();}
function getCase(k){return CASES.find(c=>c.id===state[k].id);}
function renderCase(k){const c=getCase(k),s=state[k],r=c.rounds[s.r],guard=r.rawVerdict&&r.rawVerdict!==r.verdict;let feedback=r.feedback||(guard?'原始Critic给出pass，保护规则覆盖为retrieve_more，继续检查所问目标关系。':'本轮无后续动作要求。');
const stages=c.rounds.map((x,i)=>(i?'<span class="arr">→</span>':'')+`<button data-round="${i}" data-case="${k}" class="${i===s.r?'current '+x.route:i<s.r?'done':''}"><small>第${x.n}轮</small><b>${E(x.route)}</b></button>`).join('');
const nextQuery=r.nextQuery?`<div class="query" title="${E(r.nextQuery)}">下一轮查询：${E(r.nextQuery)}</div>`:'<div class="query">本轮结束：'+E(r.outcome)+'</div>';
$('case'+k).innerHTML=`<span class="tag">实验案例回放 · ${E(c.dataset)} / ID ${c.id} · 共${c.rounds.length}轮</span><div class="case-meta">当前路由来源：<b>${E(r.routeSource)}</b></div><div class="question"><strong>${E(c.zh)}</strong><div class="en">${E(c.question)}</div></div><div class="route">${stages}</div><div class="case-grid"><div class="box"><h3>${E(r.evidenceTitle)}</h3><p>${E(r.evidence)}</p></div><div class="box"><h3>02 候选到送审答案</h3><span class="field">初始候选</span><div class="answer">${E(r.initial)}</div><span class="field">重生成结果 → 规范化后送审</span><div class="answer small-answer">${E(r.regen)} → <b>${E(r.normalized)}</b></div><div class="judge">Judge评分：${E(r.scores)}<br>投票：${E(r.votes)}</div></div><div class="box"><h3>03 Critic与控制决策</h3>${guard?'<span class="tag gold">原始Critic：'+E(r.rawVerdict)+'</span><p class="fact">保护规则覆盖 ↓</p>':''}<div class="verdict ${r.verdict==='pass'?'pass':''}">${E(r.verdict)}</div><p>${r.verdict==='pass'?'系统接受当前答案':'当前答案不满足停止条件'}</p><span class="field">本轮状态</span><p class="fact" style="overflow-wrap:anywhere">${E(r.outcome)}</p></div></div><div class="feedback"><b>${r.verdict==='pass'?'停止反馈':'为什么继续？'}</b><p>${E(feedback)}</p>${nextQuery}</div><div class="actions"><button data-reset="${k}">重置本例</button><button data-fields="${k}">展开本轮字段 / 查询</button><button class="primary" data-forward="${k}" ${s.final?'disabled':''}>${s.r<c.rounds.length-1?'查看下一轮 →':'显示最终答案与事后对照'}</button>${s.final?'<span class="result">最终：'+E(c.final)+' ｜参考：'+E(c.gold)+' ｜'+(c.correct?'匹配':'不匹配')+'</span>':''}</div>`;
}
function advanceCase(k){const s=state[k],c=getCase(k);if(s.r<c.rounds.length-1)s.r++;else s.final=true;renderCase(k);}
function raw(k){const c=getCase(k),r=c.rounds[state[k].r];$('rawContent').innerHTML='<h2>'+E(c.dataset+' / ID '+c.id+' / 第'+r.n+'轮')+'</h2><p>本轮检索、生成与验证记录</p><table>'+r.fields.map(([a,b])=>'<tr><td>'+E(a)+'</td><td>'+E(b)+'</td></tr>').join('')+'</table>'+(r.nextQuery?'<h3 style="margin-top:24px">记录中的下一轮查询（原文）</h3><p style="overflow-wrap:anywhere">'+E(r.nextQuery)+'</p>':'');$('raw').classList.add('open');}
function renderSim(){let names=['首次证据','第1轮 · graph','第2轮 · hybrid','最终对照'];$('simChips').innerHTML=names.map((n,i)=>'<span class="'+(i===simStep?'on':'')+'">'+E(n)+'</span>').join('');
$('rag').innerHTML='<h2>普通文本RAG <span class="badge">BM25 → 一次生成</span></h2><div class="tag">text · 单次检索</div><div class="evidence"><b>D01：</b>曾任Chippewa Falls市长。<br><b>D02：</b>曾在Wisconsin州议会任职。</div><p style="font-size:19px">'+(simStep===0?'首次召回只有任职经历，没有出生地关系。':'将任职地点误当成出生地，一次生成后返回。')+'</p><div class="out '+(simStep===3?'bad':'')+'">'+(simStep===0?'等待一次生成':'输出：Chippewa Falls, Wisconsin')+'</div>';
if(simStep===0)$('trace').innerHTML='<h2>TRACE-RAG <span class="badge">验证 → 反馈 → 补证据</span></h2><div class="tag">相同的模拟知识库</div><div class="evidence">初始图记录人物职业和市长任职关系，<br>没有出生地关系。</div><p class="wide">问题需要的是 <b>born in</b>，<br>不是 <b>served as mayor of</b>。</p><div class="out">检查目标关系，再决定是否停止</div>';
if(simStep===1)$('trace').innerHTML='<h2>TRACE-RAG <span class="badge">第1轮 · graph</span></h2><div class="tag gold">retrieve_more · insufficient_evidence</div><div class="evidence">初始候选：Chippewa Falls, Wisconsin<br>重生成：Insufficient information.</div><p style="font-size:20px"><b>Critic：</b>任职关系不能证明出生关系。<br><b>下一查询：</b>James M. Bingham birthplace born in</p><div class="out">graph → hybrid：补充人物传记文本</div>';
if(simStep>=2)$('trace').innerHTML='<h2>TRACE-RAG <span class="badge">第2轮 · hybrid = graph + text</span></h2><div class="tag">新增文本D03 · 直接出生地证据</div><div class="evidence direct">“James M. Bingham was <b>born in Perry, New York</b>, on February 3, 1828.”</div><p style="font-size:20px">保留任职事实作为背景；D03支持出生地。<br>重生成Perry, New York → 规范化Perry<br>Critic：<b>pass</b></p><div class="out good">最终答案：Perry</div>';
$('simPrev').disabled=simStep===0;$('simNext').disabled=simStep===3;$('simNext').textContent=simStep===2?'显示事后参考答案对照':'推进对比 →';$('simResult').textContent=simStep===3?'参考：Perry / Town of Perry ｜ 本模拟：普通RAG错误，TRACE-RAG正确':'';
}
function closeOverlay(){document.querySelectorAll('.overlay').forEach(e=>e.classList.remove('open'));}
function notes(){notesOpen=!notesOpen;$('notes').classList.toggle('open',notesOpen);}
function advance(){if(pageIndex===3)advanceCase('A');if(pageIndex===4)advanceCase('B');if(pageIndex===5){simStep=Math.min(3,simStep+1);renderSim();}}
$('arch').onclick=()=>$('zoom').classList.add('open');$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('note').onclick=notes;$('advance').onclick=advance;$('full').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});};
$('caseSelect').onchange=()=>{state.A={id:Number($('caseSelect').value),r:0,final:false};renderCase('A');};$('simPrev').onclick=()=>{simStep=Math.max(0,simStep-1);renderSim();};$('simNext').onclick=()=>{simStep=Math.min(3,simStep+1);renderSim();};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.forward)advanceCase(b.dataset.forward);if(b.dataset.reset){state[b.dataset.reset].r=0;state[b.dataset.reset].final=false;renderCase(b.dataset.reset);}if(b.dataset.fields)raw(b.dataset.fields);if(b.dataset.round!==undefined){state[b.dataset.case].r=Number(b.dataset.round);state[b.dataset.case].final=false;renderCase(b.dataset.case);}});
addEventListener('keydown',e=>{if(e.key==='Escape'){closeOverlay();return;}if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(['arrowright','pagedown'].includes(k)){e.preventDefault();move(1);}if(['arrowleft','pageup'].includes(k)){e.preventDefault();move(-1);}if(k==='home'){pageIndex=0;closeOverlay();showPage();}if(k==='n'||k===' '){e.preventDefault();advance();}if(k==='t')notes();if(k==='f')$('full').click();});
addEventListener('resize',resize);addEventListener('mousemove',showNav);resize();renderCase('A');renderCase('B');renderSim();showPage();showNav();
